name: Continuous test
on:
  push:
    branches:
      - master

jobs:
  BuildLinux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          echo "This was built on Linux." >linux.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: linux.txt
          retention-days: 2

  BuildMacOS:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          echo "This was built on MacOS." >macos.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: macos.txt
          retention-days: 2
          
  BuildWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          echo "This was built on Windows." >windows.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: windows.txt
          retention-days: 2

  UpdateAssets:
    needs: [BuildLinux, BuildMacOS, BuildWindows]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch artifacts
        uses: actions/download-artifact@v2

      - name: Rename artifacts
        run: |
          mv assets/linux.txt linux-`git describe --always`.txt
          mv assets/macos.txt macos-`git describe --always`.txt
          mv assets/windows.txt windows-`git describe --always`.txt

      - name: Upload latest pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Continuous Build"
          files: |
            linux*.txt
            macos*.txt
            windows*.txt
            LICENSE
